export {default as Contact} from './Contact/Contact'
export {default as Faq} from './Faq/Faq'
export {default as Footer} from './Footer/Footer'
export {default as Header} from './Header/Header'
export {default as Home} from './Home/Home'
export {default as Product} from './Product/Product'